modmap:
  - name: modtap
    remap:
      # Replace a key with another
      CAPSLOCK:
        held: CONTROL_L
        alone: ESC
        alone_timeout_millis: 200
      # Hook `keymap` action on key press/release events.
keymap:
  - name: vim-motions
    remap:
      ALT_R-H: LEFT
      ALT_R-J: DOWN
      ALT_R-K: UP
      ALT_R-L: RIGHT
      ALT_R-E: UP
      ALT_R-S: LEFT
      ALT_R-D: DOWN
      ALT_R-F: RIGHT
  - name: media
    remap:
      CONTROL_R-Z: VOLUMEDOWN
      CONTROL_R-X: VOLUMEUP
      CONTROL_R-C: PLAYPAUSE
      CONTROL_R-SHIFT-C: MUTE
      CONTROL_R-V: NEXTSONG
      CONTROL_R-SHIFT-V: PREVIOUSSONG
  - name: otros
    remap:
      ALT_R-BACKSPACE: DELETE
      CONTROL_R-BACKSLASH: SYSRQ
